export const ERROR_CODES = {
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    UNAUTHORIZED: 'UNAUTHORIZED',
    NOT_FOUND: 'NOT_FOUND',
    NOT_ALLOWED: 'NOT_ALLOWED',
    INVALID: 'INVALID',
    DUPLICATE: 'DUPLICATE',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
};